name: コラム投稿 (Add Column Entry)
description: 新しいコラムを追加する
title: ""
labels: ["column-entry"]
body:
  - type: input
    id: title
    attributes:
      label: タイトル
      placeholder: "例: セカイノコトワリ＠京都国立近代美術館"
    validations:
      required: true
  - type: dropdown
    id: tags
    attributes:
      label: タグ
      multiple: true
      options:
        - 研究コラム
        - 授業補足
        - 専門演習
        - 卒業研究
        - 国際社会学1
        - 国際社会学2
        - 基礎研究1
        - 基礎社会学2
        - 演習等
        - M国際車気学研究
        - 最近読んだ本
        - 学会・調査
        - 業務連絡
    validations:
      required: true
  - type: textarea
    id: body
    attributes:
      label: 本文
      description: コラムの本文を入力してください
      placeholder: "本文をここに書いてください..."
    validations:
      required: true
