name: Add Column Entry
description: Add a new column entry
body:
  - type: dropdown
    id: tags
    attributes:
      label: タグ
      multiple: true
      options:
        - 研究コラム
        - 授業補足
        - 専門演習
        - 卒業研究
        - 国際社会学1
        - 国際社会学2
        - 基礎研究1
        - 基礎社会学2
        - 演習等
        - M国際車気学研究
        - 最近読んだ本
        - 学会・調査
        - 業務連絡
    validations:
      required: true
  - type: textarea
    id: body
    attributes:
      label: 本文
      description: コラムの本文を入力してください
      placeholder: "本文をここに書いてください..."
    validations:
      required: true
